# Generated by Django 3.1.4 on 2021-01-02 17:14

from django.db import migrations, models
import helpers.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('customerID', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('inputjson', helpers.fields.JSONField(default=dict)),
            ],
        ),
    ]
