ZOHO_CLIENT_ID = ''
ZOHO_CLIENT_SECRET = ''
ZOHO_GENERATE_TOKEN = 'https://accounts.zoho.com/oauth/v2/token'
ZOHO_REFRESH_TOKEN = 'https://accounts.zoho.com/oauth/v2/token'
ZOHO_REDIRECT_URI = ''
ZOHO_AUTH_HEADER = "Authorization"
ZOHO_AUTH_TOKEN_HEADER_PREFIX = 'Zoho-authtoken '
ZOHO_ORG_ID_HEADER = "X-com-zoho-subscriptions-organizationid"
ZOHO_SUBSCRIPTION_API_URL = 'https://subscriptions.zoho.com/api/v1/'
ZOHO_PLAN_API_URL = 'https://subscriptions.zoho.com/api/v1/plans/'
ZOHO_PRODUCT_API_URL = 'https://subscriptions.zoho.com/api/v1/products/'
ZOHO_CUSTOMER_API_URL = 'https://subscriptions.zoho.com/api/v1/customers/'
ZOHO_ORG_ID = ''